/**
 * PDF Export Utilities for CANary
 * Handles PDF generation for reports and comparisons
 */

import { jsPDF } from 'jspdf';
import { TestResult } from './storage';
import { convertToExportable } from './reportExport';

const COLORS = {
  primary: [59, 130, 246] as [number, number, number],
  danger: [239, 68, 68] as [number, number, number],
  warning: [245, 158, 11] as [number, number, number],
  success: [34, 197, 94] as [number, number, number],
  muted: [107, 114, 128] as [number, number, number],
  dark: [31, 41, 55] as [number, number, number],
};

const getRiskColor = (prob: number): [number, number, number] => {
  if (prob >= 60) return COLORS.danger;
  if (prob >= 30) return COLORS.warning;
  return COLORS.success;
};

const formatDate = (d: string) => 
  new Date(d).toLocaleDateString('en-US', { year: 'numeric', month: 'short', day: 'numeric' });

/**
 * Generate PDF for a single report
 */
export const generateReportPDF = (report: TestResult): void => {
  const doc = new jsPDF();
  const exportable = convertToExportable(report);
  let yPos = 20;

  // Header
  doc.setFontSize(24);
  doc.setTextColor(...COLORS.primary);
  doc.text('CANary', 20, yPos);
  doc.setFontSize(12);
  doc.setTextColor(...COLORS.muted);
  doc.text('Cancer Risk Screening Report', 20, yPos + 8);
  
  doc.setFontSize(10);
  doc.text(`Report ID: ${report.id}`, 120, yPos);
  doc.text(`Generated: ${formatDate(report.date)}`, 120, yPos + 6);
  
  yPos += 25;

  // Disclaimer box
  doc.setFillColor(254, 243, 199);
  doc.roundedRect(15, yPos, 180, 20, 3, 3, 'F');
  doc.setFontSize(8);
  doc.setTextColor(...COLORS.dark);
  const disclaimer = doc.splitTextToSize(exportable.metadata.disclaimer, 170);
  doc.text(disclaimer, 20, yPos + 6);
  yPos += 28;

  // Risk Assessment Section
  doc.setFontSize(14);
  doc.setTextColor(...COLORS.dark);
  doc.text('Risk Assessment', 20, yPos);
  yPos += 10;

  const cancerTypes = ['pancreatic', 'colon', 'blood'] as const;
  const cancerLabels = { pancreatic: 'Pancreatic Cancer', colon: 'Colon Cancer', blood: 'Blood Cancer' };

  cancerTypes.forEach((type, index) => {
    const risk = exportable.riskAssessment[type];
    const prob = risk.probability;
    const color = getRiskColor(prob);
    
    // Risk card background
    doc.setFillColor(249, 250, 251);
    doc.roundedRect(15, yPos, 180, 25, 2, 2, 'F');
    
    // Cancer type label
    doc.setFontSize(11);
    doc.setTextColor(...COLORS.dark);
    doc.text(cancerLabels[type], 20, yPos + 8);
    
    // Risk percentage
    doc.setFontSize(16);
    doc.setTextColor(...color);
    doc.text(`${prob}%`, 150, yPos + 10);
    
    // Risk label and confidence
    doc.setFontSize(9);
    doc.setTextColor(...COLORS.muted);
    doc.text(`${risk.riskLabel} Risk • Confidence: ${risk.confidence}`, 20, yPos + 18);
    
    yPos += 30;
  });

  // Key Factors Section
  if (exportable.keyFactors.length > 0) {
    yPos += 5;
    doc.setFontSize(14);
    doc.setTextColor(...COLORS.dark);
    doc.text('Key Risk Factors', 20, yPos);
    yPos += 8;

    exportable.keyFactors.forEach((factor, i) => {
      const isIncrease = factor.impact === 'increases';
      const textColor = isIncrease ? COLORS.danger : COLORS.success;
      doc.setFontSize(10);
      doc.setTextColor(textColor[0], textColor[1], textColor[2]);
      doc.text(`${isIncrease ? '↑' : '↓'} ${factor.name}`, 25, yPos);
      doc.setTextColor(...COLORS.muted);
      doc.text(`(${factor.cancerType})`, 150, yPos);
      yPos += 6;
    });
  }

  // New page for details
  doc.addPage();
  yPos = 20;

  // Demographics
  doc.setFontSize(14);
  doc.setTextColor(...COLORS.dark);
  doc.text('Patient Demographics', 20, yPos);
  yPos += 10;

  const demoData = [
    ['Age', exportable.demographics.age?.toString() || 'N/A'],
    ['Gender', exportable.demographics.gender || 'N/A'],
    ['BMI', exportable.demographics.bmi ? `${exportable.demographics.bmi} (${exportable.demographics.bmiCategory})` : 'N/A'],
    ['Blood Group', exportable.demographics.bloodGroup || 'N/A'],
  ];

  doc.setFontSize(10);
  demoData.forEach(([label, value]) => {
    doc.setTextColor(...COLORS.muted);
    doc.text(label + ':', 25, yPos);
    doc.setTextColor(...COLORS.dark);
    doc.text(value, 70, yPos);
    yPos += 6;
  });

  // Recommendations
  yPos += 10;
  doc.setFontSize(14);
  doc.setTextColor(...COLORS.dark);
  doc.text('Recommendations', 20, yPos);
  yPos += 10;

  doc.setFontSize(10);
  exportable.recommendations.forEach((rec, i) => {
    doc.setTextColor(...COLORS.dark);
    doc.text(`${i + 1}. ${rec}`, 25, yPos);
    yPos += 7;
  });

  // Footer
  doc.setFontSize(8);
  doc.setTextColor(...COLORS.muted);
  doc.text('Generated by CANary - For research and educational purposes only', 20, 285);

  // Save
  doc.save(`CANary-Report-${formatDate(report.date)}.pdf`);
};

/**
 * Generate PDF for multiple filtered reports with trends
 */
export const generateFilteredReportsPDF = (
  reports: TestResult[],
  dateRange?: { from?: Date; to?: Date }
): void => {
  const doc = new jsPDF();
  let yPos = 20;

  // Header
  doc.setFontSize(24);
  doc.setTextColor(...COLORS.primary);
  doc.text('CANary', 20, yPos);
  doc.setFontSize(12);
  doc.setTextColor(...COLORS.muted);
  doc.text('Risk Trend Report', 20, yPos + 8);
  
  doc.setFontSize(10);
  doc.text(`Generated: ${formatDate(new Date().toISOString())}`, 120, yPos);
  if (dateRange?.from || dateRange?.to) {
    doc.text(
      `Period: ${dateRange.from ? formatDate(dateRange.from.toISOString()) : 'Start'} - ${dateRange.to ? formatDate(dateRange.to.toISOString()) : 'Present'}`,
      120, yPos + 6
    );
  }
  doc.text(`Total Reports: ${reports.length}`, 120, yPos + 12);
  
  yPos += 30;

  // Summary Table Header
  doc.setFillColor(...COLORS.primary);
  doc.rect(15, yPos, 180, 10, 'F');
  doc.setFontSize(10);
  doc.setTextColor(255, 255, 255);
  doc.text('Date', 20, yPos + 7);
  doc.text('Pancreatic', 60, yPos + 7);
  doc.text('Colon', 100, yPos + 7);
  doc.text('Blood', 140, yPos + 7);
  doc.text('Overall', 170, yPos + 7);
  yPos += 12;

  // Table rows
  reports.slice(0, 20).forEach((report, index) => {
    const preds = report.predictions;
    const pancreatic = preds?.pancreatic?.probability ?? 0;
    const colon = preds?.colon?.probability ?? 0;
    const blood = preds?.blood?.probability ?? 0;
    const maxRisk = Math.max(pancreatic, colon, blood);
    
    // Alternating row background
    if (index % 2 === 0) {
      doc.setFillColor(249, 250, 251);
      doc.rect(15, yPos - 4, 180, 8, 'F');
    }

    doc.setFontSize(9);
    doc.setTextColor(...COLORS.dark);
    doc.text(formatDate(report.date), 20, yPos);
    
    doc.setTextColor(...getRiskColor(pancreatic));
    doc.text(`${pancreatic}%`, 65, yPos);
    
    doc.setTextColor(...getRiskColor(colon));
    doc.text(`${colon}%`, 105, yPos);
    
    doc.setTextColor(...getRiskColor(blood));
    doc.text(`${blood}%`, 145, yPos);
    
    doc.setTextColor(...getRiskColor(maxRisk));
    doc.text(maxRisk >= 60 ? 'High' : maxRisk >= 30 ? 'Medium' : 'Low', 170, yPos);
    
    yPos += 8;

    // New page if needed
    if (yPos > 270) {
      doc.addPage();
      yPos = 20;
    }
  });

  // Trend Analysis
  if (reports.length >= 2) {
    yPos += 15;
    doc.setFontSize(14);
    doc.setTextColor(...COLORS.dark);
    doc.text('Trend Analysis', 20, yPos);
    yPos += 10;

    const oldest = reports[reports.length - 1];
    const newest = reports[0];
    
    const cancerTypes = ['pancreatic', 'colon', 'blood'] as const;
    cancerTypes.forEach(type => {
      const oldProb = oldest.predictions?.[type]?.probability ?? 0;
      const newProb = newest.predictions?.[type]?.probability ?? 0;
      const diff = newProb - oldProb;
      
      doc.setFontSize(10);
      doc.setTextColor(...COLORS.dark);
      doc.text(`${type.charAt(0).toUpperCase() + type.slice(1)}:`, 25, yPos);
      
      doc.setTextColor(...(diff > 2 ? COLORS.danger : diff < -2 ? COLORS.success : COLORS.muted));
      doc.text(
        `${oldProb}% → ${newProb}% (${diff > 0 ? '+' : ''}${diff.toFixed(1)}%)`,
        70, yPos
      );
      yPos += 7;
    });
  }

  // Footer
  doc.setFontSize(8);
  doc.setTextColor(...COLORS.muted);
  doc.text('Generated by CANary - For research and educational purposes only', 20, 285);

  doc.save(`CANary-Trend-Report-${formatDate(new Date().toISOString())}.pdf`);
};

/**
 * Generate PDF for comparison between two reports
 */
export const generateComparisonPDF = (reportA: TestResult, reportB: TestResult): void => {
  const doc = new jsPDF();
  let yPos = 20;

  // Header
  doc.setFontSize(24);
  doc.setTextColor(...COLORS.primary);
  doc.text('CANary', 20, yPos);
  doc.setFontSize(12);
  doc.setTextColor(...COLORS.muted);
  doc.text('Report Comparison', 20, yPos + 8);
  
  doc.setFontSize(10);
  doc.text(`Comparing: ${formatDate(reportA.date)} → ${formatDate(reportB.date)}`, 120, yPos);
  const daysDiff = Math.round(
    (new Date(reportB.date).getTime() - new Date(reportA.date).getTime()) / (1000 * 60 * 60 * 24)
  );
  doc.text(`Time Difference: ${daysDiff} days`, 120, yPos + 6);
  
  yPos += 30;

  // Risk Comparison Table
  doc.setFontSize(14);
  doc.setTextColor(...COLORS.dark);
  doc.text('Risk Probability Changes', 20, yPos);
  yPos += 10;

  // Table Header
  doc.setFillColor(...COLORS.primary);
  doc.rect(15, yPos, 180, 10, 'F');
  doc.setFontSize(10);
  doc.setTextColor(255, 255, 255);
  doc.text('Cancer Type', 20, yPos + 7);
  doc.text('Before', 80, yPos + 7);
  doc.text('After', 115, yPos + 7);
  doc.text('Change', 150, yPos + 7);
  yPos += 15;

  const cancerTypes = ['pancreatic', 'colon', 'blood'] as const;
  const cancerLabels = { pancreatic: 'Pancreatic', colon: 'Colon', blood: 'Blood' };

  cancerTypes.forEach((type, index) => {
    const probA = reportA.predictions?.[type]?.probability ?? 0;
    const probB = reportB.predictions?.[type]?.probability ?? 0;
    const diff = probB - probA;

    // Alternating row background
    if (index % 2 === 0) {
      doc.setFillColor(249, 250, 251);
      doc.rect(15, yPos - 5, 180, 10, 'F');
    }

    doc.setFontSize(10);
    doc.setTextColor(...COLORS.dark);
    doc.text(cancerLabels[type], 20, yPos);
    
    doc.setTextColor(...getRiskColor(probA));
    doc.text(`${probA}%`, 85, yPos);
    
    doc.setTextColor(...getRiskColor(probB));
    doc.text(`${probB}%`, 120, yPos);
    
    const changeColor = diff > 2 ? COLORS.danger : diff < -2 ? COLORS.success : COLORS.muted;
    doc.setTextColor(...changeColor);
    doc.text(
      `${diff > 0 ? '+' : ''}${diff.toFixed(1)}% ${diff > 2 ? '↑' : diff < -2 ? '↓' : '→'}`,
      150, yPos
    );
    
    yPos += 12;
  });

  // Factor Changes
  yPos += 15;
  doc.setFontSize(14);
  doc.setTextColor(...COLORS.dark);
  doc.text('Risk Factor Changes', 20, yPos);
  yPos += 10;

  const factorsA = new Set(reportA.rankedFactors?.map(f => f.name) || []);
  const factorsB = new Set(reportB.rankedFactors?.map(f => f.name) || []);
  
  const newFactors = reportB.rankedFactors?.filter(f => !factorsA.has(f.name)) || [];
  const removedFactors = reportA.rankedFactors?.filter(f => !factorsB.has(f.name)) || [];
  const persistentFactors = reportA.rankedFactors?.filter(f => factorsB.has(f.name)) || [];

  // New factors
  doc.setFontSize(11);
  doc.setTextColor(...COLORS.danger);
  doc.text(`New Risk Factors (${newFactors.length})`, 20, yPos);
  yPos += 7;
  
  if (newFactors.length === 0) {
    doc.setFontSize(9);
    doc.setTextColor(...COLORS.muted);
    doc.text('None', 25, yPos);
    yPos += 6;
  } else {
    newFactors.slice(0, 5).forEach(f => {
      doc.setFontSize(9);
      doc.setTextColor(...COLORS.dark);
      doc.text(`• ${f.name}`, 25, yPos);
      yPos += 5;
    });
  }

  yPos += 5;
  
  // Removed factors
  doc.setFontSize(11);
  doc.setTextColor(...COLORS.success);
  doc.text(`Resolved Factors (${removedFactors.length})`, 20, yPos);
  yPos += 7;
  
  if (removedFactors.length === 0) {
    doc.setFontSize(9);
    doc.setTextColor(...COLORS.muted);
    doc.text('None', 25, yPos);
    yPos += 6;
  } else {
    removedFactors.slice(0, 5).forEach(f => {
      doc.setFontSize(9);
      doc.setTextColor(...COLORS.dark);
      doc.text(`• ${f.name}`, 25, yPos);
      yPos += 5;
    });
  }

  yPos += 5;
  
  // Persistent factors
  doc.setFontSize(11);
  doc.setTextColor(...COLORS.warning);
  doc.text(`Persistent Factors (${persistentFactors.length})`, 20, yPos);
  yPos += 7;
  
  if (persistentFactors.length === 0) {
    doc.setFontSize(9);
    doc.setTextColor(...COLORS.muted);
    doc.text('None', 25, yPos);
  } else {
    persistentFactors.slice(0, 5).forEach(f => {
      doc.setFontSize(9);
      doc.setTextColor(...COLORS.dark);
      doc.text(`• ${f.name}`, 25, yPos);
      yPos += 5;
    });
  }

  // Summary
  yPos += 20;
  doc.setFillColor(239, 246, 255);
  doc.roundedRect(15, yPos, 180, 30, 3, 3, 'F');
  
  doc.setFontSize(11);
  doc.setTextColor(...COLORS.dark);
  doc.text('Summary', 20, yPos + 8);
  
  doc.setFontSize(9);
  doc.setTextColor(...COLORS.muted);
  
  const avgDiffBefore = (
    (reportA.predictions?.pancreatic?.probability ?? 0) +
    (reportA.predictions?.colon?.probability ?? 0) +
    (reportA.predictions?.blood?.probability ?? 0)
  ) / 3;
  
  const avgDiffAfter = (
    (reportB.predictions?.pancreatic?.probability ?? 0) +
    (reportB.predictions?.colon?.probability ?? 0) +
    (reportB.predictions?.blood?.probability ?? 0)
  ) / 3;
  
  const overallChange = avgDiffAfter - avgDiffBefore;
  const trendText = overallChange > 2 
    ? 'Overall risk has increased. Consider consulting with a healthcare provider.'
    : overallChange < -2 
    ? 'Overall risk has decreased. Continue with healthy lifestyle practices.'
    : 'Overall risk remains stable. Continue regular monitoring.';
  
  doc.text(trendText, 20, yPos + 18);

  // Footer
  doc.setFontSize(8);
  doc.setTextColor(...COLORS.muted);
  doc.text('Generated by CANary - For research and educational purposes only', 20, 285);

  doc.save(`CANary-Comparison-${formatDate(reportA.date)}-vs-${formatDate(reportB.date)}.pdf`);
};
