/**
 * Report Export Utilities for CANary
 * Handles PDF and JSON export functionality
 */

import { TestResult } from './storage';
import { PredictionResult, FeatureVector } from './predictionEngine';

export interface ExportableReport {
  metadata: {
    reportId: string;
    generatedAt: string;
    version: string;
    disclaimer: string;
  };
  demographics: {
    age?: number;
    gender?: string;
    bmi?: number;
    bmiCategory?: string;
    bloodGroup?: string;
  };
  medicalHistory: {
    familyCancerHistory: boolean;
    diabetesHistory: boolean;
    ibdHistory: boolean;
    hepatitisHistory: boolean;
    anemiaHistory: boolean;
  };
  lifestyle: {
    smoking: string;
    alcohol: string;
    sleep: string;
    physicalActivity: string;
    diet: string;
    stress: string;
  };
  symptoms: {
    general: string[];
    pancreatic: string[];
    colon: string[];
    blood: string[];
  };
  labValues: {
    hemoglobin?: { value: number; unit: string; status: string };
    wbcCount?: { value: number; unit: string; status: string };
    plateletCount?: { value: number; unit: string; status: string };
    bilirubin?: { value: number; unit: string; status: string };
    bloodSugar?: { value: number; unit: string; status: string };
  };
  riskAssessment: {
    pancreatic: {
      probability: number;
      riskLabel: string;
      confidence: string;
      explanation: string;
    };
    colon: {
      probability: number;
      riskLabel: string;
      confidence: string;
      explanation: string;
    };
    blood: {
      probability: number;
      riskLabel: string;
      confidence: string;
      explanation: string;
    };
  };
  keyFactors: {
    name: string;
    impact: string;
    cancerType: string;
  }[];
  recommendations: string[];
  featureVector?: FeatureVector;
}

/**
 * Converts a TestResult to an exportable format
 */
export const convertToExportable = (report: TestResult): ExportableReport => {
  const formData = report.formData || {};
  
  // Extract symptoms by category
  const generalSymptoms: string[] = [];
  const pancreaticSymptoms: string[] = [];
  const colonSymptoms: string[] = [];
  const bloodSymptoms: string[] = [];

  if (formData.fatigue) generalSymptoms.push('Persistent fatigue');
  if (formData.weightLoss) generalSymptoms.push('Unexplained weight loss');
  if (formData.jaundice) generalSymptoms.push('Jaundice');
  if (formData.paleSkin) generalSymptoms.push('Pale skin');
  if (formData.bruising) generalSymptoms.push('Easy bruising');

  if (formData.abdominalPain) pancreaticSymptoms.push('Upper abdominal pain');
  if (formData.backPain) pancreaticSymptoms.push('Back pain');
  if (formData.nausea) pancreaticSymptoms.push('Nausea');
  if (formData.newDiabetes) pancreaticSymptoms.push('Newly developed diabetes');
  if (formData.floatingStool) pancreaticSymptoms.push('Floating stools');

  if (formData.bloodInStool) colonSymptoms.push('Blood in stool');
  if (formData.constipation) colonSymptoms.push('Bowel changes');
  if (formData.narrowStool) colonSymptoms.push('Narrow stool');
  if (formData.bloating) colonSymptoms.push('Bloating');

  if (formData.infections) bloodSymptoms.push('Recurrent infections');
  if (formData.nosebleeds) bloodSymptoms.push('Nosebleeds');
  if (formData.bonePain) bloodSymptoms.push('Bone pain');
  if (formData.swollenLymphNodes) bloodSymptoms.push('Swollen lymph nodes');

  // Calculate BMI
  const heightM = (formData.height || 0) / 100;
  const bmi = heightM > 0 ? (formData.weight || 0) / (heightM * heightM) : 0;
  let bmiCategory = 'Unknown';
  if (bmi > 0) {
    if (bmi < 18.5) bmiCategory = 'Underweight';
    else if (bmi < 25) bmiCategory = 'Normal';
    else if (bmi < 30) bmiCategory = 'Overweight';
    else bmiCategory = 'Obese';
  }

  // Get lab value status
  const getLabStatus = (value: number | undefined, min: number, max: number): string => {
    if (value === undefined) return 'Not provided';
    if (value < min) return 'Below normal';
    if (value > max) return 'Above normal';
    return 'Normal';
  };

  // Extract ranked factors if available
  const rankedFactors = (report.predictions as any)?.rankedFactors || [];

  return {
    metadata: {
      reportId: report.id,
      generatedAt: report.date,
      version: '1.0.0',
      disclaimer: 'This report is generated by CANary, an AI research tool for educational purposes only. It is NOT a medical diagnosis and should NOT be used as a substitute for professional medical advice, diagnosis, or treatment. Always consult a qualified healthcare provider for any health concerns.',
    },
    demographics: {
      age: parseInt(formData.age) || undefined,
      gender: formData.gender || undefined,
      bmi: bmi > 0 ? Math.round(bmi * 10) / 10 : undefined,
      bmiCategory: bmi > 0 ? bmiCategory : undefined,
      bloodGroup: formData.bloodGroup || undefined,
    },
    medicalHistory: {
      familyCancerHistory: formData.familyCancerHistory || false,
      diabetesHistory: formData.diabetesHistory || false,
      ibdHistory: formData.ibdHistory || false,
      hepatitisHistory: formData.hepatitisHistory || false,
      anemiaHistory: formData.anemiaHistory || false,
    },
    lifestyle: {
      smoking: formData.smoking || 'Not specified',
      alcohol: formData.alcohol || 'Not specified',
      sleep: formData.sleep || 'Not specified',
      physicalActivity: formData.physicalActivity || 'Not specified',
      diet: formData.diet || 'Not specified',
      stress: formData.stress || 'Not specified',
    },
    symptoms: {
      general: generalSymptoms.length > 0 ? generalSymptoms : ['None reported'],
      pancreatic: pancreaticSymptoms.length > 0 ? pancreaticSymptoms : ['None reported'],
      colon: colonSymptoms.length > 0 ? colonSymptoms : ['None reported'],
      blood: bloodSymptoms.length > 0 ? bloodSymptoms : ['None reported'],
    },
    labValues: {
      hemoglobin: formData.hemoglobin ? {
        value: parseFloat(formData.hemoglobin),
        unit: 'g/dL',
        status: getLabStatus(parseFloat(formData.hemoglobin), 12, 17.5),
      } : undefined,
      wbcCount: formData.wbcCount ? {
        value: parseFloat(formData.wbcCount),
        unit: '×10⁹/L',
        status: getLabStatus(parseFloat(formData.wbcCount), 4000, 11000),
      } : undefined,
      plateletCount: formData.plateletCount ? {
        value: parseFloat(formData.plateletCount),
        unit: '×10⁹/L',
        status: getLabStatus(parseFloat(formData.plateletCount), 150000, 400000),
      } : undefined,
      bilirubin: formData.bilirubin ? {
        value: parseFloat(formData.bilirubin),
        unit: 'mg/dL',
        status: getLabStatus(parseFloat(formData.bilirubin), 0.1, 1.2),
      } : undefined,
      bloodSugar: formData.bloodSugar ? {
        value: parseFloat(formData.bloodSugar),
        unit: 'mg/dL',
        status: getLabStatus(parseFloat(formData.bloodSugar), 70, 100),
      } : undefined,
    },
    riskAssessment: {
      pancreatic: {
        probability: report.predictions.pancreatic.probability,
        riskLabel: (report.predictions.pancreatic as any).riskLabel || 
          (report.predictions.pancreatic.probability < 0.3 ? 'Low' : 
           report.predictions.pancreatic.probability < 0.6 ? 'Medium' : 'High'),
        confidence: report.predictions.pancreatic.confidence,
        explanation: (report.predictions.pancreatic as any).explanation || '',
      },
      colon: {
        probability: report.predictions.colon.probability,
        riskLabel: (report.predictions.colon as any).riskLabel || 
          (report.predictions.colon.probability < 0.3 ? 'Low' : 
           report.predictions.colon.probability < 0.6 ? 'Medium' : 'High'),
        confidence: report.predictions.colon.confidence,
        explanation: (report.predictions.colon as any).explanation || '',
      },
      blood: {
        probability: report.predictions.blood.probability,
        riskLabel: (report.predictions.blood as any).riskLabel || 
          (report.predictions.blood.probability < 0.3 ? 'Low' : 
           report.predictions.blood.probability < 0.6 ? 'Medium' : 'High'),
        confidence: report.predictions.blood.confidence,
        explanation: (report.predictions.blood as any).explanation || '',
      },
    },
    keyFactors: rankedFactors.slice(0, 5).map((f: any) => ({
      name: f.name,
      impact: f.impact,
      cancerType: f.cancerType,
    })),
    recommendations: [
      'Consult a healthcare professional to discuss these results',
      'Consider recommended screening tests (CBC, tumor markers, imaging)',
      'Maintain a healthy lifestyle with regular exercise and balanced diet',
      'Schedule follow-up screening in 3-6 months',
      'Keep a record of any new or changing symptoms',
    ],
    featureVector: (report.predictions as any)?.featureVector,
  };
};

/**
 * Generates a text report for download
 */
export const generateTextReport = (report: TestResult): string => {
  const exportable = convertToExportable(report);
  const divider = '═'.repeat(60);
  const subDivider = '─'.repeat(40);

  let content = `
${divider}
                    CANary CANCER RISK SCREENING REPORT
${divider}

Report ID: ${exportable.metadata.reportId}
Generated: ${new Date(exportable.metadata.generatedAt).toLocaleString()}
Version: ${exportable.metadata.version}

${divider}
                           IMPORTANT DISCLAIMER
${divider}
${exportable.metadata.disclaimer}

${divider}
                         SECTION 1: DEMOGRAPHICS
${divider}
Age: ${exportable.demographics.age || 'Not provided'}
Gender: ${exportable.demographics.gender || 'Not provided'}
BMI: ${exportable.demographics.bmi ? `${exportable.demographics.bmi} (${exportable.demographics.bmiCategory})` : 'Not provided'}
Blood Group: ${exportable.demographics.bloodGroup || 'Not provided'}

${divider}
                       SECTION 2: MEDICAL HISTORY
${divider}
Family Cancer History: ${exportable.medicalHistory.familyCancerHistory ? 'Yes' : 'No'}
Diabetes History: ${exportable.medicalHistory.diabetesHistory ? 'Yes' : 'No'}
IBD History: ${exportable.medicalHistory.ibdHistory ? 'Yes' : 'No'}
Hepatitis/Pancreatitis History: ${exportable.medicalHistory.hepatitisHistory ? 'Yes' : 'No'}
Anemia/Bleeding Disorders: ${exportable.medicalHistory.anemiaHistory ? 'Yes' : 'No'}

${divider}
                        SECTION 3: LIFESTYLE
${divider}
Smoking: ${exportable.lifestyle.smoking}
Alcohol: ${exportable.lifestyle.alcohol}
Sleep: ${exportable.lifestyle.sleep}
Physical Activity: ${exportable.lifestyle.physicalActivity}
Diet: ${exportable.lifestyle.diet}
Stress Level: ${exportable.lifestyle.stress}

${divider}
                       SECTION 4: SYMPTOMS
${divider}
${subDivider}
General Symptoms:
${exportable.symptoms.general.map(s => `  • ${s}`).join('\n')}

${subDivider}
Pancreatic-Related:
${exportable.symptoms.pancreatic.map(s => `  • ${s}`).join('\n')}

${subDivider}
Colon-Related:
${exportable.symptoms.colon.map(s => `  • ${s}`).join('\n')}

${subDivider}
Blood Cancer-Related:
${exportable.symptoms.blood.map(s => `  • ${s}`).join('\n')}

${divider}
                       SECTION 5: LAB VALUES
${divider}
Hemoglobin: ${exportable.labValues.hemoglobin ? `${exportable.labValues.hemoglobin.value} ${exportable.labValues.hemoglobin.unit} (${exportable.labValues.hemoglobin.status})` : 'Not provided'}
WBC Count: ${exportable.labValues.wbcCount ? `${exportable.labValues.wbcCount.value} ${exportable.labValues.wbcCount.unit} (${exportable.labValues.wbcCount.status})` : 'Not provided'}
Platelet Count: ${exportable.labValues.plateletCount ? `${exportable.labValues.plateletCount.value} ${exportable.labValues.plateletCount.unit} (${exportable.labValues.plateletCount.status})` : 'Not provided'}
Bilirubin: ${exportable.labValues.bilirubin ? `${exportable.labValues.bilirubin.value} ${exportable.labValues.bilirubin.unit} (${exportable.labValues.bilirubin.status})` : 'Not provided'}
Fasting Blood Sugar: ${exportable.labValues.bloodSugar ? `${exportable.labValues.bloodSugar.value} ${exportable.labValues.bloodSugar.unit} (${exportable.labValues.bloodSugar.status})` : 'Not provided'}

${divider}
                     SECTION 6: RISK ASSESSMENT
${divider}

╔════════════════════════════════════════════════════════════╗
║                    PANCREATIC CANCER                        ║
╠════════════════════════════════════════════════════════════╣
║  Risk Score: ${(exportable.riskAssessment.pancreatic.probability * 100).toFixed(1)}%                                       
║  Risk Level: ${exportable.riskAssessment.pancreatic.riskLabel}                                           
║  Confidence: ${exportable.riskAssessment.pancreatic.confidence}                                          
╚════════════════════════════════════════════════════════════╝
${exportable.riskAssessment.pancreatic.explanation || ''}

╔════════════════════════════════════════════════════════════╗
║                      COLON CANCER                           ║
╠════════════════════════════════════════════════════════════╣
║  Risk Score: ${(exportable.riskAssessment.colon.probability * 100).toFixed(1)}%                                       
║  Risk Level: ${exportable.riskAssessment.colon.riskLabel}                                           
║  Confidence: ${exportable.riskAssessment.colon.confidence}                                          
╚════════════════════════════════════════════════════════════╝
${exportable.riskAssessment.colon.explanation || ''}

╔════════════════════════════════════════════════════════════╗
║                      BLOOD CANCER                           ║
╠════════════════════════════════════════════════════════════╣
║  Risk Score: ${(exportable.riskAssessment.blood.probability * 100).toFixed(1)}%                                       
║  Risk Level: ${exportable.riskAssessment.blood.riskLabel}                                           
║  Confidence: ${exportable.riskAssessment.blood.confidence}                                          
╚════════════════════════════════════════════════════════════╝
${exportable.riskAssessment.blood.explanation || ''}

${divider}
                   SECTION 7: KEY CONTRIBUTING FACTORS
${divider}
${exportable.keyFactors.length > 0 
  ? exportable.keyFactors.map((f, i) => `${i + 1}. ${f.name} (${f.impact} risk for ${f.cancerType} cancer)`).join('\n')
  : 'No significant risk factors identified'}

${divider}
                    SECTION 8: RECOMMENDATIONS
${divider}
${exportable.recommendations.map((r, i) => `${i + 1}. ${r}`).join('\n')}

${divider}
                          END OF REPORT
${divider}
Generated by CANary - AI-Powered Cancer Risk Screening Tool
For research and educational purposes only.
`.trim();

  return content;
};

/**
 * Generates JSON export of the report
 */
export const generateJSONReport = (report: TestResult): string => {
  const exportable = convertToExportable(report);
  return JSON.stringify(exportable, null, 2);
};

/**
 * Downloads the report as a file
 */
export const downloadReport = (report: TestResult, type: 'text' | 'json'): void => {
  const content = type === 'json' ? generateJSONReport(report) : generateTextReport(report);
  const mimeType = type === 'json' ? 'application/json' : 'text/plain';
  const extension = type === 'json' ? 'json' : 'txt';
  const filename = `CANary-Report-${new Date(report.date).toISOString().split('T')[0]}.${extension}`;
  
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
};
